// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Test struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Age   int    `json:"age"`
	Title string `json:"title"`
}

type TestInput struct {
	Name  string `json:"name"`
	Age   int    `json:"age"`
	Title string `json:"title"`
}
